### ISSUE TITLE
Read SMS error?

### ISSUE THREAD

**Issue by yasinkiraz** [jakhax/raspberry-pi-sim800l-gsm-module#3]
Hello, When I try to read a message, I get the error in the photo, can you help me?

![image](https://user-images.githubusercontent.com/55974045/96459152-72ddd880-122a-11eb-8168-33de900d9e34.png)

**Comment by jakhax** [comment]
Hi @yasinkiraz

Can you try the following
- Make sure you have disabled serial console as per https://github.com/jakhax/raspberry-pi-sim800l-gsm-module#disable-serial-console, reboot the pi after doing so
- confirm no other process is using/blocking the port `ls -l /proc/[0-9]*/fd/* |grep /dev/serial0`

Here are some links with related problem from google

https://www.raspberrypi.org/forums/viewtopic.php?t=228315
https://github.com/pyserial/pyserial/issues/86
https://stackoverflow.com/questions/28343941/python-serialexception-device-reports-readiness-to-read-but-returned-no-data-d

**Comment by yasinkiraz** [comment]
Thank you @jakhax
